name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libjxl-dev
        sudo apt-get install -y libbrotli-dev
        sudo apt-get install libturbojpeg libturbojpeg0-dev
        sudo apt-get install libglfw3-dev
        sudo apt-get install libglew-dev

    - name: Configure CMake
      run: cmake -B build -S .
    - name: Build
      run: cmake --build build
    - name: Test
      run: cd build && ./rjp || [ $? -eq 255 ]